services:
  - type: web
    name: soderia
    env: docker
    dockerfilePath: Dockerfile.postgres
    plan: free
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
