services:
  - type: web
    name: soderia
    env: docker
    dockerfilePath: Dockerfile.postgres
    plan: free
    envVars:
      - key: DATABASE_URL
        value: "postgresql://soderia_db_j7dv_user:Gh4Zc7MZw2XNX1ehPDrintOACv6rwd0W@dpg-d6muu7fgi27c73c4kh20-a.oregon-postgres.render.com/soderia_db_j7dv"
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: "production"
